### ISSUE TITLE
Over Quota

### ISSUE THREAD

**Issue by dcunited08** [Wizehive/Firepoker#50]
Seems firepoker.io is over quota, not sure if you were aware of this issue:
`FIREBASE WARNING: The Firebase database 'firepokerio' has exceeded its quota limit and has been temporarily disabled. See https://firebase.google.com/support/faq/#database-overquota for more information. (https://firepokerio.firebaseio.com) `

**Comment by evert0n** [comment]
Thanks @dcunited08 going to take a look at it

**Comment by evert0n** [comment]
@dcunited08 seems the issue with quota as gone away for now because the billing period reset at the end of the month.

**Comment by dcunited08** [comment]
Works for me, thanks 👍

**Comment by jsdevel** [comment]
This is happening now.

**Comment by evert0n** [comment]
@jsdevel we have been hitting the limit consistently for the past months, I talked with my company last night and we are going to upgrading our Firebase plan.  Thanks
