### ISSUE TITLE
Defining an own set of estimate cards

### ISSUE THREAD

**Issue by JurMarky** [Wizehive/Firepoker#51]
Hi,
we use planning poker as a tool in our sprint planning with a distributed team to vote what story is pulled to the sprint backlog.
the team votes e.g. with three cards: ok, majority, stop
So there's a need in a planning poker tool to define a set of own cards. firepoker uses a defined set of cards.
Defining own cards would be a great enhancement. Is that a feature where you can imagine to implement it for the near future?

Thanks.

**Comment by evert0n** [comment]
Hi @JurMarky I think that would be possible, give to work on that, or feel free to send a PR, Thanks

**Comment by JurMarky** [comment]
Hi @evert0n
thank you for answering.
Unfortunately I'm not familar with web-development especially AngularJs.
Otherwise I would do that as I did it already in another github java project, too.
That's why I hope on you.  Actually I think it's only a small effort but I know ... lastly you have to spend **your** time.

**Comment by evert0n** [comment]
@JurMarky I got a bit loaded within an internal product in my job, and I could not address this yet, but as a quickly update for now I would like to research the common patterns for cards and expand the current option list, let me know if your use case is just for those 3 or if you have a diff list.

**Comment by evert0n** [comment]
Hey @JurMarky I decided step back from the idea of implementing a customisable deck of cards it's seems in your use case you are using this more like a voting app then the effort estimation.

However I did update the card options.

**Comment by JurMarky** [comment]
Hi @evert0n,
sorry that I didn't answer until now. yes, you're right.
I understand your decision.
But I'll have another issue ... comming soon ;-)

**Comment by evert0n** [comment]
Sure! You are welcome. 👍
