### ISSUE TITLE
Create Game button does not create game

### ISSUE THREAD

**Issue by canpolat** [Wizehive/Firepoker#59]
Looks like the deployed version at firepoker.io does not work any more. When I click "Create Game" the URL shows a GUID but the Game screen is not displayed (an empty white screen appears).

**Comment by evert0n** [comment]
Hey guys, hold on, I'm working on it, the problem is that we hit the quotas for the free plan again, soon than before this time.

**Comment by evert0n** [comment]
It's back work now. Thanks for your patience.

**Comment by canpolat** [comment]
@evert0n Thank you for this simple yet great tool and the prompt response.
